name = "ONKSMP"
author = "Oshi No Ko Discord Staff"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "737570d6e20b7bb54d09829def177d8aa47ed6f49d3d25eb90098ea8b301c1f3"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
