name = "Oshi No Ko SMP"
author = "Oshi No Ko Discord"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5702eca54ad2bf0c1a793c58048930c2e5b220046530f545f63b1d83426d2408"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
