name = "Oshi No Ko SMP"
author = "Oshi No Ko Discord"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93176dd61d508e79bc997935aef5c698a34fb3870fd1ba6f9fa3fec36926b0e0"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
