name = "Oshi No Ko SMP"
author = "Oshi No Ko Discord"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "474c236ca5c214e7ebee1bb42137345cac9725faf19002aea94037f974768b1b"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
