name = "ONKSMP"
author = "Oshi No Ko Discord Staff"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e05d0c93a1b36653905795309a55acf773d663509107259f0524cd4a03e6841"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
