name = "Oshi No Ko SMP"
author = "Oshi No Ko Discord"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5eda7619f9b9bccbd3a48e98b8a64229b7e0b060b561cebc894257a703a51267"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
