name = "Oshi No Ko SMP"
author = "Oshi No Ko Discord"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f99cf7d899602399b3d816331c4cb1e838d55bd92b49a23b3b7610b5f8901d5"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
