name = "ONKSMP"
author = "Oshi No Ko Discord Staff"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d18b670c76a07650ae9b1c032df7cbea5eaca5b66aa97b98fbd76b4e6be1c57"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
