name = "Oshi No Ko SMP"
author = "Oshi No Ko Discord"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba1582abb6a465659c3303d8003ecda85a18274d8ccb4b38ce96df1eb08a6ebc"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
