name = "ONKSMP"
author = "Oshi No Ko Discord Staff"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87af9c052ee4b69fe3538418d45b0b302533b36457bb8478fa1c8c520ca6f78c"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
