name = "Oshi No Ko SMP"
author = "Oshi No Ko Discord"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d141dfd93ae8650aa3263512632ef59f2f5caf149b53efc2ac313654d3401d56"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
