name = "Oshi No Ko SMP"
author = "Oshi No Ko Discord"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3669e749af7c2a28058a77718fe8b181260cfc1cdd4dc92aede236b2c467815"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
